<?php
/* @var $block \MagoArab\EasYorder\Block\Product\QuickOrder */
?>
<div class="easyorder-header">
    <h3 class="easyorder-title"><?= $block->escapeHtml($block->getFormTitle()) ?></h3>
    <p class="easyorder-subtitle"><?= __('Quick Order Process') ?></p>
    <noscript>
        <div class="message error">
            <?= __('JavaScript is required to use Quick Order.') ?>
        </div>
    </noscript>
</div>


